apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    monitoring: enabled
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-metrics1
      name: http-metrics1
  type: LoadBalancer
